// <auto-generated />
using System;
using CoinQualify.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoinQualify.Migrations
{
    [DbContext(typeof(CqContext))]
    [Migration("20211231032630_first4")]
    partial class first4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoinQualify.Models.Coin", b =>
                {
                    b.Property<int>("Coin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coin_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coin_symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Usercoin_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Usercoin_buyprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usercoin_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Usercoin_profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Usercoin_sellprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Coin_id");

                    b.HasIndex("User_id");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("CoinQualify.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("User_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_pw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoinQualify.Models.Coin", b =>
                {
                    b.HasOne("CoinQualify.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
